Closes #129. Clarifying the use of wallet string address
mit-dci/opencbdc-tx pull request #130
Opened 2022-06-09 00:21 UTC by dkgaraujo

Signed-off-by: Douglas Araujo <dkg.araujo@gmail.com>

2022-06-09 00:59 UTC, HalosGhost requested changes
I think this kind of clarity is good, but I do have a couple of requests.

I made a few suggestions inline to keep one-sentence-per-line (a gift for reviewers of diffs); but I also am a bit worried that some of the specificity might actually be a bit too rigid.

This walkthrough is meant to get people interacting with the system quickly, but this is not a production system, doesn't follow semver, and the CLI (what little of it there is) is purely for testing and demonstration. To that end, I wonder if it might make more sense (from a documentation-burden standpoint) to have more general statements (e.g., “send currency from the first wallet to the address of the second wallet created in the previous step”) which are more likely to remain evergreen.

Thoughts?

2022-06-09 00:59 UTC, HalosGhost commented on README.md
> +  Note the resulting string ("usd1qrw038lx5n4wxx3yvuwdndpr7gnm347d6pn37uywgudzq90w7fsuk52kd5u"). It is the new wallet's address, and will be used in the following step.
```suggestion
  Note the resulting string ("usd1qrw038lx5n4wxx3yvuwdndpr7gnm347d6pn37uywgudzq90w7fsuk52kd5u").
  It is the new wallet's address, and will be used in the following step.
```

2022-06-09 00:59 UTC, HalosGhost commented on README.md
> +* Send currency from one wallet to another (e.g., 30 atomic units of currency) **Note that you may need to change the wallet string in the code below ("usd1qrw0...") depending on the result of the pr
```suggestion
* Send currency from one wallet to another (e.g., 30 atomic units of currency).
  **Note that you will need to change the wallet string in the code below ("usd1qrw0...") depending on the result of the previous step.**
```

2022-06-09 00:59 UTC, HalosGhost commented on README.md
> +* Import coins to the receiving wallet. Note that the string after `importinput` is the same as the result from step above of sending the currency between wallets.
```suggestion
* Import coins to the receiving wallet.
  Note that the string after `importinput` is the same as the result from step above of sending the currency between wallets.
```

2022-06-09 05:57 UTC, dkgaraujo reviewed
Thank you for the suggestion to further simplify. It is much better indeed. I hope this new version can address that.

2022-06-09 05:57 UTC, dkgaraujo commented on README.md
> +* Import coins to the receiving wallet using the string after `importinput` from step above.
I tried to follow a similar one-line style for this string as well.

2022-06-09 20:30 UTC, dkgaraujo commented
FYI, tThe recent commits are actually a rebase because one of them was not signed off. The content is the same.

2022-06-14 23:08 UTC, dkgaraujo commented
Hi @HalosGhost, when you have some time, please feel free to let me know if there is anything outstanding from my side in this PR. I can't seem to find anything else outstanding after I pushed the simpler version.

2022-06-15 01:15 UTC, HalosGhost commented
@dkgaraujo I'm sorry about the delay! My last week or two has been quite full. I'm making time to go through all the open PRs in the next few days!

2022-06-15 07:11 UTC, dkgaraujo commented
> @dkgaraujo I'm sorry about the delay! My last week or two has been quite full. I'm making time to go through all the open PRs in the next few days!

No issue - didn't mean to press, I was just checking in case I forgot anything. Happy to proceed at your pace.

2022-06-17 16:31 UTC, HalosGhost approved these changes
Simple clarity improvement to our README walkthrough.

Looks great!

2022-06-17 16:32 UTC, HalosGhost commented
@dkgaraujo Whenever you're ready, if you can squash these to a single commit, I'll happily merge!

2022-06-21 21:53 UTC, HalosGhost commented
@dkgaraujo it looks like you merged in from `trunk`, but didn't rebase/squash. The easiest way to get yourself back to a good spot is probably (assuming you have this fork configured as a remote named `upstream` on your clone) `git pull --rebase upstream trunk`; after that point, if you still need to squash, you can do an interactive rebase.

2022-06-29 13:31 UTC, HalosGhost commented
@dkgaraujo let me know if you need help squashing.

2022-06-29 14:30 UTC, dkgaraujo commented
> @dkgaraujo let me know if you need help squashing.

@HalosGhost sorry for the delay - I had to prioritise another project. I'll come back to this by tomorrow at the latest. Thanks for the patience.

2022-06-29 14:40 UTC, HalosGhost commented
> sorry for the delay

No worries; I'll still be here to review when you're ready!

2022-07-01 00:25 UTC, dkgaraujo commented
Hi @HalosGhost, thanks again for the patience. I successfully rebased and squashed (I believe) - but in the process of interactively rebasing I noted that I went a couple of steps back from my own first commit, and when I removed the previous commits by other contributors from the interactive page, it effectively deleted them from my version of trunk. So please don't merge it. I think going back and making sure all is there would be an additional complication on this already complicated PR. Maybe we can just cancel this one and reopen another one with a simple, single commit implementing the changes? Happy to hear your views.

2022-07-10 07:14 UTC, closed without merging