Rename 3pc -> PArSEC
mit-dci/opencbdc-tx pull request #222
Opened 2023-06-21 16:08 UTC by maurermi

Renames instances of 3pc to PArSEC, includes scripts used for refactoring as well. Creating PR for review.

2023-06-21 18:17 UTC, AlexRamRam requested changes
Noticed only a few very minor misses. Looks Great

2023-06-21 18:17 UTC, AlexRamRam commented on Dockerfile
> +# Create PARSEC Deployment Image
lower-case r for consistency?

2023-06-21 18:17 UTC, AlexRamRam commented on README.md
> +We built a system that is capable of performing parallel executions of virtual machines for generic smart contract support.
How about: `We built a system with a generic virtual machine layer that is capable of performing parallel executions of smart contracts`. b/c programs/smart contracts are executed, not virtual machines

2023-06-21 18:17 UTC, AlexRamRam commented on src/parsec/runtime_locking_shard/replicated_shard_interface.hpp
> +            /// State of the ticket within the PARSEC protocol.
lowercase r for consistency?

2023-06-21 18:17 UTC, AlexRamRam commented on tests/unit/parsec/util.hpp
>  #define TEST_UNIT_THREEPC_UTIL_INC_
THREEPC --> PARSEC

2023-06-21 19:11 UTC, AlexRamRam approved these changes

2023-07-31 21:09 UTC, HalosGhost commented
Some small changes made ad-hoc; but now included in #213

2023-07-31 21:09 UTC, closed without merging