Demo guide on running Uniswap V3 on PArSEC
mit-dci/opencbdc-tx pull request #226
Opened 2023-08-09 14:37 UTC by AlexRamRam

See: docs/uniswap_demo/uniswap_demo.md

2023-08-21 17:17 UTC, maurermi requested changes
T-ACK. Uniswap on OpenCBDC!! This was fun to play with and appears to work as expected. Very excited to see this. There are just a couple of typos in the `uniswap_demo.md` file that should be fixed, and I've also included some stylistic suggestions / nits that I'd at least like looked at, but are non-blockers.

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +Install the following for your platform:
Might want to specify which version to use, or point to `.nvmrc` which specifies v18.16.0 for opencbdc-tx by default. This installation step is also specified in `parsec_user_guide.md` so could also just point there as done below.

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +Refer to the [PArSEC User Guide](../programmability_user_guide.md) on how to start the PArSEC server.
```suggestion
Refer to the [PArSEC User Guide](../parsec_user_guide.md) on how to start the PArSEC server.
```

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +cp path_to_opencbdc-tx/docs/uniswap_demo/MyTokens.sol contracts
```suggestion
cp <path_to_opencbdc-tx>/docs/uniswap_demo/MyTokens.sol contracts
```
Just to highlight that this should not be copy-pasted directly

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +cp path_to_opencbdc-tx/scripts/hardhat.config.js .
```suggestion
cp <path_to_opencbdc-tx>/scripts/hardhat.config.js .
```

Just to highlight that this should not be copy-pasted directly

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +ethers.version   // e.g. '6.6.5'
IMO would be helpful to prefix hardhat console lines with `>` for clarity. I can see the argument for not doing this since it allows copy / paste directly into the terminal (and from what I can tell, GitHub does not currently support a mechanism to mark characters as "uncopyable" in markdown files), so I'll leave this open for debate. However in our other markdown files, we have typically included the shell character ($/#/>)
```suggestion
> ethers.version   // e.g. '6.6.5'
```

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +Confirm that version of ethers.js is V6. This demo is not compatible with ethers.js V5 (***client shell*** - running hardhat console)
Clarity
```suggestion
Confirm that the major version of ethers.js is V6. This demo is not compatible with ethers.js V5 (***client shell*** - running hardhat console)
```

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +signers[0].address
Should assign this value to a var or specify that it should be noted since it's used later

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +const weth  = await ethers.deployContract('WETHToken', [ethers.parseEther('10000')]);
nit: could be helpful to specify what the observed output should be for each command (if there is an expected output)

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +rm -f state.json
```suggestion
rm -f state.json # created after running index.js
```

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +    address: '0x...',
nit

```suggestion
    address: '0x...', # take note of this value
```

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +    address: '0x...',
nit 

```suggestion
    address: '0x...', # take note of this value
```

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +This step is needed as the uniswap deploy script only deploy the V2 router.
Typo

```suggestion
This step is needed as the uniswap deploy script only deploys the V2 router.
```

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +const UNISWAPV3FACTORY_ADDR = '0x...'                      // NonfungiblePositionManager contract address
The comments identifying the purpose of the variables are flipped

2023-08-21 17:17 UTC, maurermi commented on docs/uniswap_demo/uniswap_demo.md
> +swap_receipt0 = await swap_resp.wait();
```suggestion
swap_receipt0 = await swap_resp0.wait();
```

2023-08-24 21:39 UTC, AlexRamRam commented on docs/uniswap_demo/uniswap_demo.md
> +rm -f state.json
Will note: `In case index.js is run more than once`

2023-08-24 21:48 UTC, AlexRamRam commented on docs/uniswap_demo/uniswap_demo.md
> +const weth  = await ethers.deployContract('WETHToken', [ethers.parseEther('10000')]);
Motivation is good, but given the verbosity of the EVM outputs will affect readability and length ...

2023-08-25 14:35 UTC, maurermi approved these changes
T-ACK, all previous comments have been addressed, in my opinion this is ready to merge

2023-08-25 14:41 UTC, AlexRamRam commented
> T-ACK, all previous comments have been addressed, in my opinion this is ready to merge

Thank you for going through this and contributing.

2023-08-25 16:24 UTC, merged