Remove sudo in build
mit-dci/opencbdc-tx pull request #232
Opened 2023-09-21 13:36 UTC by madars

Currently, `./scripts/configure.sh` requires root privileges to build OpenCBDC. These privileges are used for three purposes:
a) installing build environment (e.g. clang, gmake on macOS, etc);
b) installing certain packaged dependencies (e.g. GoogleTest/`libgtest-dev`); and
c) after fetching and compiling sources from the internet, installing certain libraries (e.g. LevelDB, NuRaft, Lua, etc) into OS default install path (usually, `/usr/lib`).

This is suboptimal in multiple ways. First, invocation of sudo is spread all the way through the script, making this dependency harder to audit. Second, installing user-compiled dependencies in `/usr/lib` can interfere with OS package management (e.g., when user has already installed Lua) and makes it harder to develop two OpenCBDC instances side by side, if one of them, for example, wants to bump up its dependencies (e.g. have a never version of evmc).

The two commits below try to amend the above as follows:
- We split out installing build environment (a) and OS packages (b) into a separate script, `./scripts/install-build-tools.sh`. This script requires `sudo`.
- We also adjust `./scripts/configure.sh` to install dependencies in a separate, user-owned prefix directory (currently, this is called `prefix` and lives alongside `build` directory). This makes installation of these dependencies (c) not rely on root privileges and separates them between different instances of OpenCBDC (and system itself).
- We adjust `./scripts/build.sh` and `CMakeLists.txt` to include this prefix directory in dependency search.

If this looks good, I can also produce appropriate changes to the documentation (README.md).

2023-09-21 15:28 UTC, HalosGhost commented
*strong* concept ACK. It looks like the commits are missing a DCO, and it does look like a large portion of the CI workflows need to be updated.

2023-09-22 14:23 UTC, HalosGhost commented
This looks great, but I believe there might be a small issue to resolve: I get linker errors from the static `libcurl.a` put in `prefix/`. Looks like it's expecting to find nghttp2 and openldap; are these expected to be compiled in statically, or installed from the new build-dependencies script?

<details>

```
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `http2_disconnect':
http2.c:(.text+0xbc): undefined reference to `nghttp2_session_del'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `http2_getsock':
http2.c:(.text+0x114): undefined reference to `nghttp2_session_want_write'
/usr/bin/ld: http2.c:(.text+0x124): undefined reference to `nghttp2_session_get_remote_window_size'
/usr/bin/ld: http2.c:(.text+0x148): undefined reference to `nghttp2_session_get_stream_remote_window_size'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `on_begin_headers':
http2.c:(.text+0x178): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `on_header':
http2.c:(.text+0x1d5): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/bin/ld: http2.c:(.text+0x4f0): undefined reference to `nghttp2_submit_rst_stream'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `on_stream_close':
http2.c:(.text+0x5da): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/bin/ld: http2.c:(.text+0x62c): undefined reference to `nghttp2_session_set_stream_user_data'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `on_data_chunk_recv':
http2.c:(.text+0x6af): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `data_source_read_callback':
http2.c:(.text+0x7ea): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `h2_session_send':
http2.c:(.text+0x9b0): undefined reference to `nghttp2_priority_spec_init'
/usr/bin/ld: http2.c:(.text+0xa02): undefined reference to `nghttp2_submit_priority'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `h2_process_pending_input':
http2.c:(.text+0xaa4): undefined reference to `nghttp2_session_mem_recv'
/usr/bin/ld: http2.c:(.text+0xae3): undefined reference to `nghttp2_session_check_request_allowed'
/usr/bin/ld: http2.c:(.text+0xb25): undefined reference to `nghttp2_session_want_read'
/usr/bin/ld: http2.c:(.text+0xb32): undefined reference to `nghttp2_session_want_write'
/usr/bin/ld: http2.c:(.text+0xba2): undefined reference to `nghttp2_strerror'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `http2_conncheck':
http2.c:(.text+0xd1d): undefined reference to `nghttp2_submit_ping'
/usr/bin/ld: http2.c:(.text+0xd45): undefined reference to `nghttp2_session_send'
/usr/bin/ld: http2.c:(.text+0xd56): undefined reference to `nghttp2_strerror'
/usr/bin/ld: http2.c:(.text+0xd7b): undefined reference to `nghttp2_strerror'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `http2_handle_stream_close':
http2.c:(.text+0xf34): undefined reference to `nghttp2_http2_strerror'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `http2_recv':
http2.c:(.text+0x1111): undefined reference to `nghttp2_session_want_read'
/usr/bin/ld: http2.c:(.text+0x1126): undefined reference to `nghttp2_session_want_write'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `http2_send':
http2.c:(.text+0x1453): undefined reference to `nghttp2_session_resume_data'
/usr/bin/ld: http2.c:(.text+0x145a): undefined reference to `nghttp2_is_fatal'
/usr/bin/ld: http2.c:(.text+0x1474): undefined reference to `nghttp2_is_fatal'
/usr/bin/ld: http2.c:(.text+0x15ce): undefined reference to `nghttp2_priority_spec_init'
/usr/bin/ld: http2.c:(.text+0x1669): undefined reference to `nghttp2_submit_request'
/usr/bin/ld: http2.c:(.text+0x16cb): undefined reference to `nghttp2_session_want_read'
/usr/bin/ld: http2.c:(.text+0x16ec): undefined reference to `nghttp2_session_resume_data'
/usr/bin/ld: http2.c:(.text+0x1738): undefined reference to `nghttp2_session_want_read'
/usr/bin/ld: http2.c:(.text+0x174c): undefined reference to `nghttp2_session_want_write'
/usr/bin/ld: http2.c:(.text+0x1788): undefined reference to `nghttp2_session_want_write'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `Curl_http2_ver':
http2.c:(.text+0x186f): undefined reference to `nghttp2_version'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `on_frame_recv':
http2.c:(.text+0x1a24): undefined reference to `nghttp2_session_get_stream_user_data'
/usr/bin/ld: http2.c:(.text+0x1a6d): undefined reference to `nghttp2_submit_rst_stream'
/usr/bin/ld: http2.c:(.text+0x1a74): undefined reference to `nghttp2_is_fatal'
/usr/bin/ld: http2.c:(.text+0x1a9d): undefined reference to `nghttp2_session_get_remote_settings'
/usr/bin/ld: http2.c:(.text+0x1ab0): undefined reference to `nghttp2_session_get_remote_settings'
/usr/bin/ld: http2.c:(.text+0x1f0c): undefined reference to `nghttp2_submit_rst_stream'
/usr/bin/ld: http2.c:(.text+0x1f13): undefined reference to `nghttp2_is_fatal'
/usr/bin/ld: http2.c:(.text+0x1fbb): undefined reference to `nghttp2_session_set_stream_user_data'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `Curl_http2_done':
http2.c:(.text+0x2171): undefined reference to `nghttp2_submit_rst_stream'
/usr/bin/ld: http2.c:(.text+0x21ab): undefined reference to `nghttp2_session_set_stream_user_data'
/usr/bin/ld: http2.c:(.text+0x2200): undefined reference to `nghttp2_session_send'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `Curl_http2_request_upgrade':
http2.c:(.text+0x22ca): undefined reference to `nghttp2_pack_settings_payload'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `Curl_http2_done_sending':
http2.c:(.text+0x241c): undefined reference to `nghttp2_session_want_write'
/usr/bin/ld: http2.c:(.text+0x244b): undefined reference to `nghttp2_session_want_write'
/usr/bin/ld: http2.c:(.text+0x2475): undefined reference to `nghttp2_session_resume_data'
/usr/bin/ld: http2.c:(.text+0x2491): undefined reference to `nghttp2_session_want_write'
/usr/bin/ld: /home/halosghost/prj/desudoization/prefix/lib/libcurl.a(libcurl_la-http2.o): in function `Curl_http2_setup':
http2.c:(.text+0x2612): undefined reference to `nghttp2_session_callbacks_new'
/usr/bin/ld: http2.c:(.text+0x262a): undefined reference to `nghttp2_session_callbacks_set_send_callback'
/usr/bin/ld: http2.c:(.text+0x263a): undefined reference to `nghttp2_session_callbacks_set_on_frame_recv_callback'
/usr/bin/ld: http2.c:(.text+0x264a): undefined reference to `nghttp2_session_callbacks_set_on_data_chunk_recv_callback'
/usr/bin/ld: http2.c:(.text+0x265a): undefined reference to `nghttp2_session_callbacks_set_on_stream_close_callback'
/usr/bin/ld: http2.c:(.text+0x266a): undefined reference to `nghttp2_session_callbacks_set_on_begin_headers_callback'
/usr/bin/ld: http2.c:(.text+0x267a): undefined reference to `nghttp2_session_callbacks_set_on_header_callback'
/usr/bin/ld: http2.c:(.text+0x268a): undefined reference to `nghttp2_session_callbacks_set_error_callback'
/usr/bin/ld: http2.c:(.text+0x269d): undefined reference to `nghttp2_session_client_ [...]

2023-09-28 20:21 UTC, HalosGhost requested changes
needs rebase, and potentially a fix regarding another dependency (see comment above).

2024-01-08 16:18 UTC, maurermi commented
Just going to make a comment for future reference: this removes sudo in configure, our build script does not require sudo

2024-01-11 04:23 UTC, anders94 commented
Not to pile on too much here but I'd suggest renaming `./scripts/configure.sh` to something like `./scripts/install-dependencies.sh` while we're at it.

2024-03-01 16:24 UTC, HalosGhost commented
merged via #249

2024-03-01 16:24 UTC, closed without merging