readme improvements
mit-dci/opencbdc-tx pull request #277
Opened 2024-07-07 21:20 UTC by eolesinski

This PR makes various improvements to the project's `README.md`

- adds more detail to installation section
- adds additional sections (documentation, etc.)
- minor spelling fixes and phrasing changes

2024-07-07 22:20 UTC, maurermi requested changes
This looks good to me, but in general we try to not include binary files in this repo -- if you could convert the image from png format to svg that I think should make this good to go!

2024-07-07 22:20 UTC, maurermi commented on docs/opencbdc_logo.png
Looks great, but in general we aim to not check in any binaries in this repo -- our m.o. has been to include images as .svg files thus far, so if you could convert this, that would be great!

2024-07-08 15:07 UTC, maurermi approved these changes
ACK, looks good on my end, a couple nit-picky comments that would be great to address IMO but I am comfortable with this as is

2024-07-08 15:07 UTC, maurermi commented on README.md
> +# Installation
nit: I think we should change this to Setup instead of install -- I think that may more accurately describe what's going on here

2024-07-08 15:07 UTC, maurermi commented on README.md
> +   Because the installation is done in a user-specific location (`./prefix` by default) rather than a system-wide one, you do not need administrative (root) permission to run the script. Additionally
nit: Can probably just say root permission instead of administrative (root) permission

2024-07-08 15:07 UTC, maurermi commented on README.md
> +Users can run both unit/integration and end-to-end tests on OpenCBDC.
nit: I would be inclined to say something like "verify setup by running tests on OpenCBDC" instead of "Users can run ..."

2024-07-09 20:12 UTC, HalosGhost requested changes
I have a very few small requests to keep everything inline with current standards. None of it should be onerous.

2024-07-09 20:12 UTC, HalosGhost commented on README.md
>  The API Reference is now housed in [an external repository](https://github.com/mit-dci/opencbdc-tx-pages/).
Let's move this line down to the Documentation section; it's a bit out of place here.

2024-07-09 20:12 UTC, HalosGhost commented on README.md
> +The official documentation for OpenCBDC can be found here: [OpenCBDC-tx-pages](https://mit-dci.github.io/opencbdc-tx-pages/)
```suggestion
Github Pages hosts the official copy of the OpenCBDC [API Reference](https://mit-dci.github.io/opencbdc-tx-pages/).
```

This rephrasing is mostly just to 1) clarify what documentation is at the link, and 2) avoid the “here” idiom that makes screen-reader-users' lives far less pleasant.

2024-07-09 20:12 UTC, HalosGhost commented on README.md
> +   Because the installation is done in a user-specific location (`./prefix` by default) rather than a system-wide one, you do not need root permission to run the script. Additionally, if you want to
```suggestion
   Because the installation is done in a user-specific location (`./prefix` by default) rather than a system-wide one, you do not need root permission to run the script.
   Additionally, if you want to remove the installed build-dependencies or restart the installation process, you can safely delete the `prefix` directory and rerun this script.
```

In general, for any document-rendering process that swallows newlines (as in $\LaTeX$, or most markdown engines (including GFM)), if you're storing the document in-`git`, everything is easier (particularly reviewing diffs) if you keep to one complete thought (or sentence, at most) on a line.

2024-07-09 20:12 UTC, HalosGhost commented on README.md
> +See the [Documentation](#documentation) section below to browse.
After moving the above line to the Documentation section, I think this can be safely deleted.

2024-07-15 20:01 UTC, HalosGhost approved these changes
Thanks for handling all my little nits! This looks good to me. Will merge once CI finishes.

2024-07-15 20:27 UTC, merged