docs: Correct statistics in README
mit-dci/opencbdc-tx pull request #41
Opened 2022-02-09 17:34 UTC by HalosGhost

The statistics in the README are outdated, and do not refer to the
latest demonstrated numbers in the technical paper.

This minor change corrects the statistics to match the paper
appropriately.

2022-02-09 19:24 UTC, anders94 commented
Good catch. I don't think we need to stipulate "(as of release of the technical paper)" though. In the future that might be slightly ambiguous.

2022-02-09 19:28 UTC, HalosGhost commented
@anders94 the reason I put in that parenthetical was so that we wouldn't need to keep updating the numbers if they change. Do you have a thought about how we can keep them evergreen?

2022-02-09 19:30 UTC, metalicjames approved these changes

2022-02-09 19:30 UTC, metalicjames commented on README.md
>      - Geo-replicated latency ~3 seconds.
I think we said <2 s in the paper.

2022-02-09 19:44 UTC, anders94 commented
@HalosGhost Yeah, good point. Short answer is "no" - we'll have to remember to update here as things change.

2022-02-09 19:45 UTC, anders94 requested changes
Per James' note, let's update to <2 seconds latency. Otherwise LGTM.

2022-02-09 19:45 UTC, anders94 commented on README.md
>      - Geo-replicated latency ~3 seconds.
Agreed. Let's update this as well.

2022-02-09 19:49 UTC, HalosGhost commented
Requesting final double-check before merge!

2022-02-10 21:59 UTC, anders94 approved these changes
LGTM

2022-02-10 22:18 UTC, merged