build: Check for buildtime support of cpu features
mit-dci/opencbdc-tx pull request #44
Opened 2022-02-09 20:45 UTC by theuni

Addresses #42, though libsecp256k1 could use some feature detection as well. I suspect build is currently broken for 32bit targets.

Additionally, tests should be added for sse42 and crc for leveldb, but I don't believe their absence is causing any current build problems.

2022-02-09 21:59 UTC, theuni commented
Test failure appears to be a false positive.

2022-02-10 22:36 UTC, HalosGhost requested changes
@theuni We're working on getting the DCO check added to the CI so this check will happen automatically, but these commits do not contain a sign-off. Would you mind either amending both commits with a sign-off (`git commit --amend -s`) or squashing and signing-off on the squashed commit?

2022-02-11 20:15 UTC, HalosGhost commented
@metalicjames I think this is an excellent improvement to the build system, but would love a second set of eyes to review before I merge it.

2022-02-11 20:17 UTC, HalosGhost approved these changes
Separates out several x86-focused instruction sets and tests for their availability before actually leveraging them.

I think the idea is excellent and the implementation looks good. I'd like to get someone else to review quickly since cmake isn't the build-system I'm most familiar with.

2022-02-14 20:59 UTC, metalicjames approved these changes
I tested this PR locally on a Raspberry Pi running Ubuntu. With this patch I can configure and build the project out of the box.

2022-02-14 23:41 UTC, HalosGhost commented
Looks good on several counts. Merging!

2022-02-14 23:42 UTC, merged