Add Docker Publishing Workflow
mit-dci/opencbdc-tx pull request #76
Opened 2022-03-10 14:06 UTC by kylecrawshaw

Adding a Github Actions Workflow to publish Docker images to Github Container Registry. Images will be published with the branch name, `latest` and commit sha only on the default branch. In this case every time a branch is merged into `trunk` there will be a new Docker image published with the tags `sha-<commit>`, `latest` and `trunk`.

Signed-off-by: Kyle Crawshaw <kyle.crawshaw@gmail.com>

2022-03-10 16:09 UTC, HalosGhost requested changes
Speaking with @kylecrawshaw offline, this is an excellent idea, but a couple of small improvements/simplifications are possible, and associated documentation will make it all much easier for people to leverage.

2022-04-01 21:01 UTC, kylecrawshaw commented
-  I've added a new file called `docker-compose-dev-2pc.yml` that only containers the image and build args necessary to make sure that docker compose will be build a local image.
- The changes to `docker-compose-2pc.yml` will ensure that docker compose uses a pre-built image from Github Container Registry.
    - The benefit of this change is that it will be significantly faster to get up and running with the system if you are not making any code changes.
- `README.md` has been updated with a new section for `Development` that explains how to run the system with both docker-compose files

2022-04-04 19:07 UTC, jallen-frb approved these changes
Looks good to me. I think this will greatly improve image management.

2022-04-04 19:40 UTC, HalosGhost requested changes
I have a couple of small nit-picky formatting things. I will try to pull these changes this week to test and hopefully give the final okay for merging.

2022-04-04 19:40 UTC, HalosGhost commented on README.md
> +We publish new docker images for all commits to `trunk`. You can find the images [in the Github Container Registry](https://github.com/mit-dci/opencbdc-tx/pkgs/container/opencbdc-tx).
```suggestion
We publish new docker images for all commits to `trunk`.
You can find the images [in the Github Container Registry](https://github.com/mit-dci/opencbdc-tx/pkgs/container/opencbdc-tx).
```

2022-04-04 19:40 UTC, HalosGhost commented on README.md
> +_The below configuration uses the pre-built image from Github Container Registry. To run and test your changes to the codebase you can follow the [Development section](#development)._
```suggestion
_The below configuration uses the pre-built image from Github Container Registry.
To run and test your changes to the codebase you can follow the [Development section](#development)._
```

2022-04-04 19:42 UTC, kylecrawshaw commented
> I have a couple of small nit-picky formatting things. I will try to pull these changes this week to test and hopefully give the final okay for merging.

Thanks for the suggested changes. These both make sense. I'll update now.

2022-04-05 20:53 UTC, closed without merging

2022-04-05 20:59 UTC, HalosGhost commented
@kylecrawshaw, following the correction mentioned in the NEWS post, this PR needs to be rebased.