Don't imports inputs not sent to the current wallet
mit-dci/opencbdc-tx pull request #79
Opened 2022-03-15 04:58 UTC by JonWiggins

Hi,

I took at swing at fixing #54. I did this by mirroring how a similar check is done in `transaction::wallet::sign`. I thought about splitting it off into a common method that could be both places, but I didn't want to mess with the other operations done with the lock in the `sign` function.

Let me know what you think. I'm happy to make any needed changes if this seems like a plausible solution.

Thanks

Signed-off-by: Jon Wiggins <me@jonwiggins.org>

2022-03-17 14:58 UTC, HalosGhost commented
Welcome! I will dive in and review today.

2022-03-17 23:16 UTC, HalosGhost requested changes
Pulling and testing locally, this looks like it solves the issue quite well. So, I only have a couple of small logistical requests:

* Can you rephrase and shorten your commit header (less than 50 characters)? I might suggest something like “fix: Avoid importing unspendable inputs” though the new title for the PR you chose would also be fine
* Can you include `closes #54` in the body of the commit message? (this will result in the issue auto-closing when this gets merged.)

More information on why we prefer these kinds of conventions can be found in our [getting started guide](https://github.com/mit-dci/opencbdc-tx/blob/trunk/docs/getting-started.md#what-does-a-good-commit-look-like).

Aside from these small issues, this looks like an excellent first contribution, and I look forward to merging it!

2022-03-18 02:06 UTC, JonWiggins commented
Great, thanks.
I've made those changes. And I'll keep an eye out for future issues I think I can help to fix.

2022-03-18 13:49 UTC, HalosGhost commented
> I've made those changes.

Thank you! Sorry to ask for another small change, but each section of the commit message needs to be separated by an empty line (namely, the `Signed-off-by` trailer needs to have a newline between it and the message body; similarly, the commit message header needs a newline between it and the message body).

2022-03-18 13:52 UTC, jonwiggins commented
Whoops, sorry about that.

How about now?

2022-03-18 13:55 UTC, HalosGhost commented
Perfect. I'll let the CI run one last time and then merge it today!

2022-03-18 17:25 UTC, HalosGhost approved these changes
Very simple and clean check to only import an input into a wallet if the input is spendable by the wallet.

Looks good to me!

2022-03-18 17:25 UTC, merged